/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2025-12-11T13:49:49.004Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | Author
    | Blogpost
    | Category
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | AuthorHydrated
    | BlogpostHydrated
    | CategoryHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | AuthorHydratedTwice
    | BlogpostHydratedTwice
    | CategoryHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | AuthorBase
    | BlogpostBase
    | CategoryBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region author

  export interface AuthorBase extends BaseObject<"author"> {
    name: string;
    avatar?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>
      | Array<InternalMediaBase>;
  }

  export interface Author extends AuthorBase {
    avatar?: Array<DataLink>;
  }

  export interface AuthorHydrated extends AuthorBase {
    avatar?: Array<InternalMedia>;
  }

  export interface AuthorHydratedTwice extends AuthorBase {
    avatar?: Array<InternalMediaHydrated>;
  }

  export namespace Author {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "avatar" | "avatar[*].type" | "avatar[*].dataUrl"
    >;
  }

  // #endregion

  // #region blogpost

  export interface BlogpostBase extends BaseObject<"blogpost"> {
    title: string;

    /**
     * Slug can only have alphanumerical characters, - and _
     */
    slug: string;
    seo_title?: string;
    seo_keywords?: string;
    seo_meta_description?: string;
    headerImage:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>
      | Array<InternalMediaBase>;
    read_time?: number;
    lead: string;
    content: string;
    author:
      | Array<DataLink>
      | Array<Author>
      | Array<AuthorHydrated>
      | Array<AuthorHydratedTwice>
      | Array<AuthorBase>;
    category:
      | Array<DataLink>
      | Array<Category>
      | Array<CategoryHydrated>
      | Array<CategoryHydratedTwice>
      | Array<CategoryBase>;
    __translations?: Array<Blogpost._translationsBase>;
  }

  export interface Blogpost extends BlogpostBase {
    headerImage: Array<DataLink>;
    author: Array<DataLink>;
    category: Array<DataLink>;
    __translations?: Array<Blogpost._translations>;
  }

  export interface BlogpostHydrated extends BlogpostBase {
    headerImage: Array<InternalMedia>;
    author: Array<Author>;
    category: Array<Category>;
    __translations?: Array<Blogpost._translationsHydrated>;
  }

  export interface BlogpostHydratedTwice extends BlogpostBase {
    headerImage: Array<InternalMediaHydrated>;
    author: Array<AuthorHydrated>;
    category: Array<CategoryHydrated>;
    __translations?: Array<Blogpost._translationsHydratedTwice>;
  }

  export namespace Blogpost {
    export type FilterableFields = StringWithAutocomplete<
      | "title"
      | "slug"
      | "seo_title"
      | "seo_keywords"
      | "seo_meta_description"
      | "headerImage"
      | "headerImage[*].type"
      | "headerImage[*].dataUrl"
      | "read_time"
      | "lead"
      | "content"
      | "author"
      | "author[*].type"
      | "author[*].dataUrl"
      | "category"
      | "category[*].type"
      | "category[*].dataUrl"
      | "__translations"
      | "__translations[*].title"
      | "__translations[*].slug"
      | "__translations[*].seo_title"
      | "__translations[*].seo_keywords"
      | "__translations[*].seo_meta_description"
      | "__translations[*].headerImage"
      | "__translations[*].headerImage[*].type"
      | "__translations[*].headerImage[*].dataUrl"
      | "__translations[*].read_time"
      | "__translations[*].lead"
      | "__translations[*].content"
      | "__translations[*].author"
      | "__translations[*].author[*].type"
      | "__translations[*].author[*].dataUrl"
      | "__translations[*].category"
      | "__translations[*].category[*].type"
      | "__translations[*].category[*].dataUrl"
      | "__translations[*].__language"
    >;

    // #region Blogpost.__translations

    export interface _translationsBase {
      title: string;

      /**
       * Slug can only have alphanumerical characters, - and _
       */
      slug: string;
      seo_title?: string;
      seo_keywords?: string;
      seo_meta_description?: string;
      headerImage:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>
        | Array<InternalMediaBase>;
      read_time?: number;
      lead: string;
      content: string;
      author:
        | Array<DataLink>
        | Array<Author>
        | Array<AuthorHydrated>
        | Array<AuthorHydratedTwice>
        | Array<AuthorBase>;
      category:
        | Array<DataLink>
        | Array<Category>
        | Array<CategoryHydrated>
        | Array<CategoryHydratedTwice>
        | Array<CategoryBase>;
      __language: string;
    }

    export interface _translations extends _translationsBase {
      headerImage: Array<DataLink>;
      author: Array<DataLink>;
      category: Array<DataLink>;
    }

    export interface _translationsHydrated extends _translationsBase {
      headerImage: Array<InternalMedia>;
      author: Array<Author>;
      category: Array<Category>;
    }

    export interface _translationsHydratedTwice extends _translationsBase {
      headerImage: Array<InternalMediaHydrated>;
      author: Array<AuthorHydrated>;
      category: Array<CategoryHydrated>;
    }

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        | "title"
        | "slug"
        | "seo_title"
        | "seo_keywords"
        | "seo_meta_description"
        | "headerImage"
        | "headerImage[*].type"
        | "headerImage[*].dataUrl"
        | "read_time"
        | "lead"
        | "content"
        | "author"
        | "author[*].type"
        | "author[*].dataUrl"
        | "category"
        | "category[*].type"
        | "category[*].dataUrl"
        | "__language"
      >;
    }

    // #endregion
  }

  // #endregion

  // #region category

  export interface CategoryBase extends BaseObject<"category"> {
    name: string;
    color: "blue" | "green" | "yellow" | "indigo";
    __translations?: Array<Category._translationsBase>;
  }

  export interface Category extends CategoryBase {
    __translations?: Array<Category._translations>;
  }

  export interface CategoryHydrated extends CategoryBase {
    __translations?: Array<Category._translationsHydrated>;
  }

  export interface CategoryHydratedTwice extends CategoryBase {
    __translations?: Array<Category._translationsHydratedTwice>;
  }

  export namespace Category {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "color"
      | "__translations"
      | "__translations[*].name"
      | "__translations[*].color"
      | "__translations[*].__language"
    >;

    // #region Category.__translations

    export interface _translationsBase {
      name: string;
      color: "blue" | "green" | "yellow" | "indigo";
      __language: string;
    }

    export interface _translations extends _translationsBase {}

    export interface _translationsHydrated extends _translationsBase {}

    export interface _translationsHydratedTwice extends _translationsBase {}

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        "name" | "color" | "__language"
      >;
    }

    // #endregion
  }

  // #endregion

  export interface FlotiqObjectAPI {
    author: ApiRequest<
      Author,
      AuthorHydrated,
      AuthorHydratedTwice,
      Author.FilterableFields
    >;

    blogpost: ApiRequest<
      Blogpost,
      BlogpostHydrated,
      BlogpostHydratedTwice,
      Blogpost.FilterableFields
    >;

    category: ApiRequest<
      Category,
      CategoryHydrated,
      CategoryHydratedTwice,
      Category.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
